//
//  RCUITableViewPositonConstMacros.h
//  RCUIKit
//
//  Created by Kingle Zhuang on 5/18/12.
//  Copyright 2012 RingCentral, Inc. All rights reserved.
//

#import <RCUIKit/RCUIGlobalCommon.h>


#define RCUI_TABLEVIEW_GROUP_LEFT_MARGIN_PHONE						8
#define RCUI_TABLEVIEW_GROUP_RIGHT_MARGIN_PHONE						\
	RCUI_TABLEVIEW_GROUP_LEFT_MARGIN_PHONE
#define RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN_PHONE					10
#define RCUI_TABLEVIEW_GROUP_CELL_RIGHT_MARGIN_PHONE				\
	RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN_PHONE
#define RCUI_TABLEVIEW_SIMPLE_CELL_HEIGHT_PHONE						48
#define RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN_PHONE				12
#define RCUI_TABLEVIEW_SIMPLE_CELL_RIGHT_MARGIN_PHONE				\
	RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN_PHONE
#define RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN_PHONE					10
#define RCUI_TABLEVIEW_SIMPLE_CELL_BOTTOM_MARGIN_PHONE				\
	RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN_PHONE
#define RCUI_TABLEVIEW_SIMPLE_CELL_HORIZONTAL_SPACE_PHONE			10
#define RCUI_TABLEVIEW_SIMPLE_CELL_VERTICAL_SPACE_PHONE				8

#define RCUI_TABLEVIEW_CELL_SUBVALUE_WIDTH_PHONE					70
#define RCUI_TABLEVIEW_CELL_INDEX_WIDTH_PHONE						32
#define RCUI_TABLEVIEW_CELL_RADIUS_PHONE							6


#define RCUI_TABLEVIEW_GROUP_LEFT_MARGIN_PAD						45
#define RCUI_TABLEVIEW_GROUP_RIGHT_MARGIN_PAD						\
	RCUI_TABLEVIEW_GROUP_LEFT_MARGIN_PAD
#define RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN_PAD					14
#define RCUI_TABLEVIEW_GROUP_CELL_RIGHT_MARGIN_PAD					\
	RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN_PAD
#define RCUI_TABLEVIEW_SIMPLE_CELL_HEIGHT_PAD						54
#define RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN_PAD					12
#define RCUI_TABLEVIEW_SIMPLE_CELL_RIGHT_MARGIN_PAD					\
	RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN_PAD
#define RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN_PAD					10
#define RCUI_TABLEVIEW_SIMPLE_CELL_BOTTOM_MARGIN_PAD				\
	RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN_PAD
#define RCUI_TABLEVIEW_SIMPLE_CELL_HORIZONTAL_SPACE_PAD				20
#define RCUI_TABLEVIEW_SIMPLE_CELL_VERTICAL_SPACE_PAD				10

#define RCUI_TABLEVIEW_CELL_SUBVALUE_WIDTH_PAD						90
#define RCUI_TABLEVIEW_CELL_INDEX_WIDTH_PAD						    32
#define RCUI_TABLEVIEW_CELL_RADIUS_PAD								10


#define RCUI_TABLEVIEW_GROUP_LEFT_MARGIN							(RCUIIsIPAD () ? RCUI_TABLEVIEW_GROUP_LEFT_MARGIN_PAD : RCUI_TABLEVIEW_GROUP_LEFT_MARGIN_PHONE)
#define RCUI_TABLEVIEW_GROUP_RIGHT_MARGIN							(RCUIIsIPAD () ? RCUI_TABLEVIEW_GROUP_RIGHT_MARGIN_PAD : RCUI_TABLEVIEW_GROUP_RIGHT_MARGIN_PHONE)
#define RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN						(RCUIIsIPAD () ? RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN_PAD : RCUI_TABLEVIEW_GROUP_CELL_LEFT_MARGIN_PHONE)
#define RCUI_TABLEVIEW_GROUP_CELL_RIGHT_MARGIN						(RCUIIsIPAD () ? RCUI_TABLEVIEW_GROUP_CELL_RIGHT_MARGIN_PAD : RCUI_TABLEVIEW_GROUP_CELL_RIGHT_MARGIN_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_HEIGHT							(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_HEIGHT_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_HEIGHT_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN						(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_LEFT_MARGIN_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_RIGHT_MARGIN						(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_RIGHT_MARGIN_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_RIGHT_MARGIN_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN						(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_TOP_MARGIN_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_BOTTOM_MARGIN					(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_BOTTOM_MARGIN_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_BOTTOM_MARGIN_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_HORIZONTAL_SPACE					(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_HORIZONTAL_SPACE_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_HORIZONTAL_SPACE_PHONE)
#define RCUI_TABLEVIEW_SIMPLE_CELL_VERTICAL_SPACE					(RCUIIsIPAD () ? RCUI_TABLEVIEW_SIMPLE_CELL_VERTICAL_SPACE_PAD : RCUI_TABLEVIEW_SIMPLE_CELL_VERTICAL_SPACE_PHONE)

#define RCUI_TABLEVIEW_CELL_SUBVALUE_WIDTH							(RCUIIsIPAD () ? RCUI_TABLEVIEW_CELL_SUBVALUE_WIDTH_PAD : RCUI_TABLEVIEW_CELL_SUBVALUE_WIDTH_PHONE)
#define RCUI_TABLEVIEW_CELL_INDEX_WIDTH							    (RCUIIsIPAD () ? RCUI_TABLEVIEW_CELL_INDEX_WIDTH_PAD : RCUI_TABLEVIEW_CELL_INDEX_WIDTH_PHONE)
#define RCUI_TABLEVIEW_CELL_RADIUS									(RCUIIsIPAD () ? RCUI_TABLEVIEW_CELL_RADIUS_PAD : RCUI_TABLEVIEW_CELL_RADIUS_PHONE)
